# install.packages("renv")
renv::init()
if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("EnrichedHeatmap")
BiocManager::install("rtracklayer")
install.packages("restfulr")
BiocManager::install("LOLA")
install.packages("simpleCache")
BiocManager::install("BSgenome.Mmusculus.UCSC.mm10")
BiocManager::install("annotatr")
