---
title: "sc5hmC_hotspot_repeat"
output: html_notebook
author: "Sherry Xue"
date: "2025-03-13"
---

```{r setup}
knitr::opts_knit$set(root.dir = "F:/Gitee/sc5hmC/")
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

library(dplyr)
library(LOLA)
library(dplyr)
library(ggplot2)
library(GenomicRanges)
```

```{r lib}
mouse_TE_JC_age_fn <- "F:/Project/sc5hmC/data/ref/mm10_TE_JCage.tsv"
control_fn <- "data/processed/hotspot.cpg_density_matched.rds"
hotspot_fn <- "data/source/1111_hmC_ratio_1X50.merge.1k.v5s4.hotspot.bed"
merged_fn <- "data/processed/hotspot.5hmC.1X50.240218.rds"
```

```{r func}
run_lola <- function(
    x, control_region = c("matched", "genomic_tile"), 
    test_gr, ctrl_gr, add_age=F,
    return_plot = TRUE, return_res = TRUE){

  regionDB <- loadRegionDB("F:/packages/LOLACore/mm10/", collections = x)

  userSets <- GRangesList(test_gr)
  names(userSets) <- "hotspot"

  if(control_region=="matched"){

    locResults <- runLOLA(
      userSets,
      # merged_gr,
      c(test_gr, ctrl_gr),
      regionDB,
      minOverlap = 1,
      direction = "enrichment"
    )

  }else if(control_region=="genomic_tile"){
    require(EnrichedHeatmap)

    chr_df <-  circlize::read.chromInfo(species="mm10")$df
    chr_gr <- GRanges(
      seqnames = chr_df[, 1],
      ranges = IRanges(chr_df[, 2] + 1, chr_df[, 3])
    )
    chr_window <- makeWindows(chr_gr, w = unique(width(test_gr)))

    locResults <- runLOLA(
      userSets,
      # merged_gr,
      c(test_gr, chr_window),
      regionDB,
      minOverlap = 1,
      direction = "enrichment"
    )
  }
  
  if(add_age){
    
    locResults <- locResults %>%
      left_join(mouse_TE_age_summary, by=c("description"="name")) 
    
    p <- locResults %>%
      mutate(label = ifelse(qValue < 0.05, description, "")) %>%
      ggplot(aes(x = oddsRatio, y = -log10(qValue))) +
      geom_point(aes(color=mya), size = 2) +
      scale_color_viridis_c(direction = -1) + 
      ggrepel::geom_text_repel(
        aes(label = label),box.padding = 0.5,max.overlaps = Inf) +
      theme_classic(base_size = 15) +
      theme(aspect.ratio = 1,
            legend.position = "bottom")
  }else {
    p <- locResults %>%
    mutate(label=ifelse(qValue < 0.05, description, "")) %>%
    ggplot(aes(x=oddsRatio, y=-log10(qValue)))+
    geom_point(size=2, shape=21, color="#f698b5")+
    ggrepel::geom_text_repel(
      aes(label=label),box.padding = 0.5, max.overlaps =Inf)+
    theme_classic(base_size = 15) +
    theme(aspect.ratio = 1)
  }

  if(!return_res & !return_plot) {
    out <- list(plot=p, res=locResults)
  }else if((!return_res) & return_plot) {
    
    plot_time <- strsplit(as.character(Sys.time()), " ")[[1]][1]
    fn_1 <- paste0("data/processed/hotspot.lola_", x, ".", plot_time, ".rds")
    saveRDS(locResults, fn_1)
    
    return(p)
  }else if(return_res & (!return_plot)) {
    # fn_2 <- paste0("viz/hotspot.lola_", x, ".", plot_time, ".pdf")

    # ggsave(
    #   plot = p,
    #   filename = fn_2,
    #   width = 10,
    #   height = 10,
    #   units = "cm"
    # )
    
    return(locResults)
  }
  else return(NULL)
}
```

```{r load hotspot}
control_gr <- readRDS(control_fn)
hotspot_gr <- readBed(hotspot_fn)
merged_gr <- readRDS(merged_fn)
```

```{r load TE age}
## evolutionary age of TEs
mouse_TE_age <- read.table(mouse_TE_JC_age_fn, stringsAsFactors = F)
colnames(mouse_TE_age) <- c(
  "chromosome_name", "start_position", "end_position",
  "name", "repFamily", "repClass", "strand",
  "substitution_proportion", "jc_distance"
)
# substitution rate of mouse genome from Waterston et al., 2002
mouse_TE_age$jc_distance <- as.numeric(mouse_TE_age$jc_distance)
mouse_TE_age$mya <- (mouse_TE_age$jc_distance*100)/(4.5*2*100)*1000

# filter repeat annotation file
mouse_TE_age$repFamily <- gsub("\\?","", mouse_TE_age$repFamily)
mouse_TE_age$repClass <- gsub("\\?","", mouse_TE_age$repClass)

mouse_TE_age_summary <- mouse_TE_age %>%
  group_by(name, repClass, repFamily) %>%
  summarise(mya = mean(mya)) %>% arrange(mya)
```

```{r run lola, fig.width=8, fig.height=4}
p1 <- run_lola("rmsk_gene", "matched", hotspot_gr, control_gr, return_plot = T, return_res = F)
p2 <- run_lola("rmsk_family", "matched", hotspot_gr, control_gr, return_plot = T, return_res = F)
p3 <- run_lola("rmsk_LINE", "matched", hotspot_gr, control_gr, add_age = T, return_plot = T, return_res = F)
p4 <- run_lola("rmsk_LTR", "matched", hotspot_gr, control_gr, add_age = T, return_plot = T, return_res = F)

cowplot::plot_grid(p1, p2, align = "v", nrow = 1)
# ggsave("viz/hotspot.lola_rmsk_1.250211.pdf", width = 12, height = 4)
cowplot::plot_grid(p3, p4, align = "v", nrow = 1)
# ggsave("viz/hotspot.lola_rmsk_2.250211.pdf", width = 12, height = 4)
```

