---
title: "sc5hmC_hotspot_signal"
output: html_notebook
author: "Sherry Xue"
date: "2025-05-10"
---

```{r setup}
knitr::opts_knit$set(root.dir = "F:/Gitee/sc5hmC/")
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

library(dplyr)
library(ggplot2)
library(GenomicRanges)
library(MatchIt)
library(data.table)
```

```{r lib}
hotspot_fn <- "data/processed/1111_hmC_ratio_1X50.merge.1k.v5s4.hotspot.bed"
cpg_density_fn <- "data/metadata/mm10.CpG_density.win1k.noN.rds"
```

```{r pal}
region_pal <- c("hotspot"="#7ca9d5", "matched"="#e7df68", "other"="#e5545b")
```

```{r func}
plot_hotspot_hmC <- function(hotspot_rds, y_axis_title, plot_name){

  merged_gr <- readRDS(hotspot_rds)

  merged_long <- merged_gr %>%
    as.data.table() %>%
    dplyr::select(`X2C`, `X4C`, `X8C`, `Morula`, `Blast`, `region`) %>%
    reshape2::melt(id.var="region") %>%
    filter(!is.na(value))

  merged_long$region <- factor(
    merged_long$region,
    levels = c("other", "matched", "hotspot")
  )

  p <- merged_long %>%
    ggplot(aes(x=region, y=value, color=region))+
    geom_jitter(aes(group=region),shape=21, width = .3) +
    geom_violin(scale = "width", fill=NA, color="black") +
    facet_wrap(.~variable, nrow = 2, scales = "free") +
    # scale_x_discrete(guide = "axis_nested") +
    scale_color_manual(values = region_pal) +
    labs(y=y_axis_title) +
    egg::theme_presentation(base_size = 15) +
    theme(aspect.ratio = 1,
          axis.ticks.x = element_blank(),
          axis.text.x = element_text(angle = 45, hjust = 1),
          axis.title.x = element_blank())

  # ggsave(
  #   plot = p,
  #   filename = plot_name,
  #   width = 12,
  #   height = 6
  # )

  return(p)
}
```

```{r match cpg density, eval=FALSE, include=FALSE}
## load input
hotspot_gr <- LOLA::readBed(hotspot_fn)
seqlevels(hotspot_gr) <- hotspot_gr %>%
  seqnames %>% unique %>% stringr::str_sort(numeric = T)
hotspot_gr <- sort(hotspot_gr)

cpg_density <- readRDS(cpg_density_fn)
cpg_density

seqlevels(cpg_density)
cpg_density <- sort(cpg_density)

## add CpG density
hits <- findOverlaps(hotspot_gr, cpg_density)
cpg_density$hotspot <- 0
cpg_density$hotspot[hits@to] <- 1
table(cpg_density$hotspot)

## sample non-hotspot regions
non_hotspot_gr <- cpg_density %>% .[.$hotspot==0]
non_hotspot_gr <- non_hotspot_gr[sample(length(non_hotspot_gr), size = 5e4)]

sampled_gr <- c(
  cpg_density %>% .[.$hotspot==1],
  non_hotspot_gr
)
seqlevels(sampled_gr)
sampled_gr <- sort(sampled_gr)

gc()

## stat hotspot against cpg_density
wilcox.test(
  sampled_gr %>% .[.$hotspot == 1] %>% .$cpg_density,
  sampled_gr %>% .[.$hotspot == 0] %>% .$cpg_density,
  alternative = "less"
) ## p-value = 6.693e-06

## matching
m.out1 <- matchit(
  hotspot ~ cpg_density,
  data = sampled_gr %>% as.data.table(),
  method = "nearest",
  distance = "glm", link = "probit"
)
summary(m.out1)

gc()

plot(
  m.out1, type = "jitter",
  interactive = FALSE
)
plot(
  m.out1, type = "density",
  interactive = FALSE,
  which.xs = ~ cpg_density
)

wilcox.test(
  get_matches(m.out1) %>% subset(hotspot==1) %>% .$cpg_density,
  get_matches(m.out1) %>% subset(hotspot==0) %>% .$cpg_density,
  alternative = "less"
) # p-value = 0.5

control_gr <- get_matches(m.out1) %>%
  subset(hotspot==0) %>%
  makeGRangesFromDataFrame()
control_gr <- sort(control_gr)
control_gr

# saveRDS(control_gr, file = "data/processed/hotspot.cpg_density_matched.rds")
```


```{r plot, fig.width=8, fig.height=6}
plot_hotspot_hmC(
  "data/processed/hotspot.5hmC.1X50.240218.rds",
  y_axis_title = "5hmCpG level"
)
plot_hotspot_hmC(
  "data/processed/hotspot.5hmC_5mC_nor.1X50.240218.rds",
  y_axis_title = "5hmCpG/5mCpG level"
)
```

```{r}
sessionInfo()
```

