---
title: "sc5hmC_genewise_correlation"
output: html_notebook
author: "Sherry Xue"
date: "2025-05-10"
---

```{r setup}
knitr::opts_knit$set(root.dir = "F:/Gitee/sc5hmC/")
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

library(dplyr)
library(ggplot2)
library(ggpubr)
library(egg)
library(EnrichedHeatmap)
library(rtracklayer)
library(data.table)
```

```{r lib}
gene_list_fn <- "data/processed/Gene_wise_cor.5hmC_5mC.20240217.tsv"
k36me3_preimplant_dir <- "data/processed/h3k36me3_genebody/"
k27me3_preimplant_dir <- "data/processed/H3K27me3_genebody/"
gene_anno_fn <- "data/metadata/mm10.gencode.p4.protein_coding.bed"
cpg_density_fn <- "data/metadata/mm10.genebody.cpg_density.rds"
k4me3_2C_fn <- "data/public/GSM1845268_2cell_late_K4me3_rep1.bed"
pol2_pn5_fn <- "data/public/GSM4010568_PN5_RP_rep1.mm10.bw"
pol2_L2C_fn <- "data/public/GSM4010572_2cell_late_RP_rep1.mm10.bw"
k36me3_L2C_fn <- "data/public/Late_2C_H3K36me3.bw"
k27me3_2C_fn <- "data/public/GSM2082673_2cell.H3K27me3.1.bedGraph"
mc_mtx_fn <- "data/processed/mC.genebody_mtx.tsv"
hmc_mtx_fn <- "data/processed/hmC.genebody_mtx.tsv"
rna_mtx_fn <- "data/processed/RNA.genebody_mtx.tsv"
```

```{r pal}
gene_cat_pal <- c("pos"="#e51d17", "neg"="#3d51a2", "none"="grey30")
stage_pal <- c(
  "Zygote" = "#5092c6", "Two.cell"="#f47f70", "Four.cell"="#f7b463",
  "Eight.cell" = "#b5df6e", "Morula"="#f9cce4", "Blast"="#d9d9d9",
  "Oocyte" = "#94d3c8", "Sperm" = "#da9dfd"
)
```

```{r summary of genes by category, fig.width=4, fig.height=4}
gene_cor_res <- read.table(gene_list_fn, header = T, stringsAsFactors = F)

pos_genes <- gene_cor_res %>%
  filter(pval < 0.05 & rho > 0) %>%
  pull(gene)
length(pos_genes)
neg_genes <- gene_cor_res %>%
  filter(pval < 0.05 & rho < 0) %>%
  pull(gene)
length(neg_genes)

gene_cor_res %>%
  ggplot(aes(x=rho, y=-log10(pval)))+
  geom_point(aes(color=group), shape=21, size=3) +
  geom_hline(yintercept = -log10(0.05), linetype="longdash") +
  geom_vline(xintercept = 0, linetype="longdash") +
  scale_color_manual(values = gene_cat_pal) +
  theme_bw(base_size = 15) +
  theme(aspect.ratio = 1)
```

```{r check 5hmC & 5mC, fig.width=8, fig.height=4}
mc_mtx <- read.table(mc_mtx_fn, header = T, stringsAsFactors = F)
rownames(mc_mtx) <- mc_mtx$gene
hmc_mtx <- read.table(hmc_mtx_fn, header = T, stringsAsFactors = F)
rownames(hmc_mtx) <- hmc_mtx$gene
rna_mtx <- read.table(rna_mtx_fn, header = T, stringsAsFactors = F)
rownames(rna_mtx) <- rna_mtx$gene

plot_MO_genes <- function(genes){

  plot_df <- rbind(
    hmc_mtx %>% .[genes,] %>% reshape2::melt() %>%
      mutate(omic="5hmC") %>% filter(value < 0.03),
    rna_mtx %>% .[genes,] %>% reshape2::melt() %>%
      mutate(omic="RNA") %>% filter(value < 0.03),
    mc_mtx %>% .[genes,] %>% reshape2::melt() %>%
      mutate(omic="5mC") %>% filter(value < 0.3)
  )
  plot_df$variable <- factor(
    plot_df$variable,
    levels =
      c("gene",
        "Oocyte",
        "Sperm",
        "Zygote",
        "Two.cell",
        "Four.cell",
        "Eight.cell",
        "Morula",
        "Blast")
  )

  p <- plot_df %>%
    # filter(variable %in% colnames(hmc_mtx)[3:ncol(hmc_mtx)]) %>%
    ggplot(aes(x=variable, y=value))+
    # ggbeeswarm::geom_quasirandom(aes(color=variable)) +
    geom_violin(aes(color=variable), scale = "width", size=1) +
    geom_boxplot(aes(color=variable), outlier.shape = NA, width=.3, size=1) +
    facet_wrap(.~omic, scales = "free", nrow=1) +
    scale_color_manual(values = stage_pal) +
    labs(y="Modification/Expression") +
    theme_presentation(base_size = 15) +
    theme(aspect.ratio = 1,
          legend.position = "none",
          axis.text.x = element_text(angle = 45, hjust = 1),
          axis.title.x = element_blank())

  # p1
  return(p)
}


plot_MO_genes(pos_genes) + 
  ggtitle("Positively correlated genes") +
  theme(plot.title = element_text(hjust = .5))
plot_MO_genes(neg_genes) + 
  ggtitle("Negatively correlated genes") +
  theme(plot.title = element_text(hjust = .5))
```

```{r CpG density, fig.width=7, fig.height=4}
cpg_density_gr <- readRDS(cpg_density_fn)

cpg_density_gr$gene_cat <- case_when(
  cpg_density_gr$gene %in% pos_genes ~ "pos",
  cpg_density_gr$gene %in% neg_genes ~ "neg",
  TRUE ~ "no_sig"
)
plot_df <- inner_join(
  gene_cor_res,
  cpg_density_gr %>% as.data.frame(),
  by = c("gene")
)

plot_df %>%
  dplyr::select(group, cpg_density, width) %>%
  reshape2::melt(id.var="group") %>%
  filter(group!="none") %>%
  ggplot(aes(x=group, y=log10(value)))+
  geom_violin(aes(color=group)) +
  geom_boxplot(aes(color=group), outlier.shape = NA, size=1, width=.3) +
  scale_color_manual(values = c("pos"="#e51d17", "neg"="#3d51a2", "none"="grey30")) +
  ggpubr::stat_compare_means(comparisons = list(c("pos", "neg"))) +
  facet_wrap(.~variable, scale="free_y") +
  egg::theme_presentation(base_size = 15)+
  theme(aspect.ratio = 1.2)
```


```{r cor with H3K36me3, fig.width=6, fig.height=4}
k36_mtx <- lapply(
  list.files(k36me3_preimplant_dir, full.names = T),
  function(x){
    df <- read.table(x, header = F, stringsAsFactors = F)
    sp <- strsplit(basename(x), "[.]")[[1]][1]
    colnames(df) <- c("chr", "start", "end", "gene", sp)
    df <- df %>% .[,c("gene", sp)]
    # print(sapply(df, class))
    return(df)
  }
)

k36_mtx <-
  k36_mtx %>% purrr::reduce(function(x, y)
    base::merge(x, y, by = c("gene"))) %>%
  filter(Biobase::isUnique(gene)) %>%
  filter(complete.cases(.))

plot_df <- inner_join(
  k36_mtx, gene_cor_res, by="gene") %>%
  dplyr::select(group, `1C`, `Late_2C`, `8C`, `ICM`) %>%
  reshape2::melt(id.var="group") %>%
  filter(group!="none")

stat.test <- plot_df %>%
  group_by(variable) %>%
  summarise(pval=wilcox.test(value~group)$p.value)
stat.test

plot_df %>%
  ggplot(aes(x=variable, y=value))+
  geom_boxplot(aes(color=group), outlier.shape = 21, size=1) +
  scale_color_manual(values = gene_cat_pal) +
  annotate(
    "text", label = format(stat.test$pval, digit=2),
    x = stat.test$variable, y = 4.8) +
  labs(y="Averaged signals", title = "H3K36me3")+
  theme_classic(base_size = 15)+
  theme(aspect.ratio = 2/3,
        plot.title = element_text(hjust = .5),
        axis.title.x = element_blank())
```

```{r cor with H3K27me3, fig.width=6, fig.height=4}
k27_mtx <- lapply(
  list.files(k27me3_preimplant_dir, full.names = T), function(x) {
  df <- read.table(x, header = F, stringsAsFactors = F)
  sp <- strsplit(basename(x), "[.]")[[1]][1]
  # sp <- strsplit(sp, "_")[[1]][1]
  colnames(df) <- c("chr", "start", "end", "gene", sp)
  df <- df %>% .[, c("gene", sp)]
  # print(sapply(df, class))
  return(df)
})

k27_mtx <-
  k27_mtx %>% purrr::reduce(function(x, y)
    base::merge(x, y, by = c("gene"))) %>%
  filter(Biobase::isUnique(gene)) %>%
  filter(complete.cases(.)) %>%
  reshape2::melt(id.var = "gene") %>%
  mutate(variable = stringr::str_split(variable, "_", simplify = T)[, 2]) %>%
  group_by(gene, variable) %>%
  summarise(value_avg = mean(value)) %>%
  ungroup() %>%
  tidyr::spread(value = value_avg, key = variable)

plot_df <- inner_join(k27_mtx, gene_cor_res, by = "gene") %>%
  dplyr::select(-rho, -pval, -gene) %>%
  reshape2::melt(id.var = "group") %>%
  filter(group != "none")

stage_order <- c("2cell", "4cell", "8cell", 'morula', 'ICM', 'TE')

stat.test <- plot_df %>%
  group_by(variable) %>%
  summarise(pval = wilcox.test(value ~ group)$p.value) %>%
  arrange(variable, levels = stage_order)
stat.test

plot_df$variable <- factor(plot_df$variable, levels = stage_order)

plot_df %>%
  ggplot(aes(x=variable, y=value))+
  geom_boxplot(aes(color=group), outlier.shape = 21, size=1) +
  # geom_hline(yintercept = 0, linetype="longdash") +
  scale_color_manual(values = gene_cat_pal) +
  ylim(c(0,0.4)) +
  annotate(
    "text", label = format(stat.test$pval, digit=2),
    x = stat.test$variable, y = 0.37) +
  labs(y="Averaged signals", title = "H3K27me3")+
  theme_classic(base_size = 15)+
  theme(aspect.ratio = 2/3,
        plot.title = element_text(hjust = .5),
        axis.title.x = element_blank())
```

```{r coord. of genes}
genes_gr <- fread(gene_anno_fn) %>%
  setNames(c("seqnames", "start", "end", "ensembl", "symbol", "strand")) %>%
  distinct(symbol, .keep_all = TRUE) %>%
  filter(symbol %in% c(pos_genes, neg_genes)) %>%
  mutate(
    cor = case_when(
      symbol %in% pos_genes ~ "pos",
      symbol %in% neg_genes ~ "neg"),
    seqnames = paste0("chr", seqnames)) %>%
  makeGRangesFromDataFrame(keep.extra.columns = T) %>%
  .[seqnames(.) %in% paste0("chr", c(1:19, "X", "Y", "MT")),]
genes_gr

tss <- promoters(genes_gr, upstream = 0, downstream = 1)
tss
```

```{r cor with other omics(heatmap), fig.width=12}
line_col <- gene_cat_pal[c("pos", "neg")]
top_anno <- HeatmapAnnotation(lines = anno_enriched(gp = gpar(col = rev(line_col))))

h3k4me3 <- import(k4me3_2C_fn)
h3k4me3$score <- as.numeric(h3k4me3$name)
h3k4me3

mat0 <-  normalizeToMatrix(
  h3k4me3, tss, value_column = "score",
  extend = 3000, mean_mode = "absolute", w = 50,
  keep = c(0, 0.99)
)
mat0
rm(h3k4me3)

ht0 <- EnrichedHeatmap(
  mat0, col = c("white", "orange"),
  name = "H3K4me3",
  top_annotation = top_anno,
  row_split = tss$cor,
  column_title = "H3K4me3(L2C)",
  width=unit(4,"cm"),
  use_raster=T,
  raster_resize_mat=mean,
  raster_quality = 3,
  heatmap_legend_param = list(
    # direction = "horizontal",
    border = "black",
    legend_height = unit(2, "cm")
  )
)
# ht0

pol2_E2C <- import(pol2_pn5_fn)
pol2_E2C

mat1 <-  normalizeToMatrix(
  pol2_E2C, tss, value_column = "score",
  extend = 3000, mean_mode = "w0", w = 50,
  keep = c(0, 0.99)
)
# mat1
rm(pol2_E2C)

pol2_E_col_fun <- circlize::colorRamp2(
  c(0, max(mat1)), c("white", "darkgreen")
)
top_anno_pol <- HeatmapAnnotation(
  lines = anno_enriched(
    gp = gpar(col = rev(line_col)),
    ylim = c(0,8),
    axis_param = list(
    side = "right",
    at = seq(2,8,2),
    labels = seq(2,8,2))
  )
)

ht1 <- EnrichedHeatmap(
  mat1, col = pol2_E_col_fun,
  name = "PolII_ZY",
  top_annotation = top_anno_pol,
  row_split = tss$cor,
  column_title = "PolII(PN5)",
  width=unit(4,"cm"),
  use_raster=T,
  raster_resize_mat=mean,
  raster_quality = 3,
  heatmap_legend_param = list(
    # direction = "horizontal",
    border = "black",
    legend_height = unit(2, "cm")
  )
)
# ht1

pol2_L2C <- import(pol2_L2C_fn)
pol2_L2C

mat2 <-  normalizeToMatrix(
  pol2_L2C, tss, value_column = "score",
  extend = 3000, mean_mode = "w0", w = 50,
  keep = c(0, 0.99)
)
# mat2
rm(pol2_L2C)

ht2 <- EnrichedHeatmap(
  mat2, col = pol2_E_col_fun,
  name = "PolII_L2C",
  top_annotation = top_anno_pol,
  row_split = tss$cor,
  column_title = "PolII(L2C)",
  width=unit(4,"cm"),
  use_raster=T,
  raster_resize_mat=mean,
  raster_quality = 3,
  heatmap_legend_param = list(
    # direction = "horizontal",
    border = "black",
    legend_height = unit(2, "cm")
  )
)
# ht1 + ht2

h3k36me3 <- import(k36me3_L2C_fn)
h3k36me3

mat4 <-  normalizeToMatrix(
  h3k36me3, genes_gr, value_column = "score",
  extend = 3000, mean_mode = "w0", w = 50,
  keep = c(0, 0.99)
)
# mat4
rm(h3k36me3)

ht4 <- EnrichedHeatmap(
  mat4, col = c("white", "blue"),
  name = "H3K36me3",
  top_annotation = top_anno,
  row_split = tss$cor,
  column_title = "H3K36me3(L2C)",
  width=unit(4,"cm"),
  use_raster=T,
  raster_resize_mat=mean,
  raster_quality = 3,
  heatmap_legend_param = list(
    # direction = "horizontal",
    border = "black",
    legend_height = unit(2, "cm")
  )
)

h3k27me3 <- import(k27me3_2C_fn)
h3k27me3

mat5 <-  normalizeToMatrix(
  h3k27me3, genes_gr, value_column = "score",
  extend = 3000, mean_mode = "w0", w = 50,
  keep = c(0, 0.99)
)
# mat5
rm(h3k27me3)

ht5 <- EnrichedHeatmap(
  mat5, col = c("white", "red"),
  name = "H3K27me3",
  top_annotation = top_anno,
  row_split = tss$cor,
  column_title = "H3K27me3(2C)",
  width=unit(4,"cm"),
  use_raster=T,
  raster_resize_mat=mean,
  raster_quality = 3,
  heatmap_legend_param = list(
    # direction = "horizontal",
    border = "black",
    legend_height = unit(2, "cm")
  )
)

lgd <- Legend(
  at = names(line_col),
  title = "Genes", type = "lines",
  legend_gp = gpar(col = line_col)
)

# pdf("viz/Gene_wise_cor.heatmap.240402.pdf", width = 12, height = 6)
draw(
  ht1 + ht2 + ht0 + ht4 + ht5,
  annotation_legend_list = list(lgd),
  ht_gap = unit(c(10,10,10,10), "mm"),
  heatmap_legend_side = "right"
)
# dev.off()
```

```{r}
sessionInfo()
```

