---
title: "sc5hmC_hotspot_repeat"
output: html_notebook
author: "Sherry Xue"
date: "2025-05-10"
---

```{r setup}
knitr::opts_knit$set(root.dir = "F:/Gitee/sc5hmC/")
knitr::opts_chunk$set(warning = TRUE, message = FALSE)
library(magrittr)
library(dplyr)
library(data.table)
library(ggplot2)
```

```{r pal}
fill_pal <- c("stable"="grey", "decreasing"="#74b1d8", "increasing"="#df6c77")
```

```{r load data}
plot_dt <- readRDS("data/processed/DhMR.sc_5k.rds")
mc_df <- read.table(
  "data/processed/WGBS_GSR.5000_1X.merged.bed",
  header = T, stringsAsFactors = F
)
```

```{r plot, fig.width=15, fig.height=4}
plot_5mc_5hmC_ratio <- function(stage_pair){
  
  # stage_pair <- "2C->4C"

  cmp_list <- colnames(mc_df)[-c(1:3)]
  names(cmp_list) <- c("ZY", "2C", "4C", "8C", "Morula", "Blast")

  pre_stage <- cmp_list[strsplit(stage_pair, "->")[[1]][1]]
  pro_stage <- cmp_list[strsplit(stage_pair, "->")[[1]][2]]
  
  tmp_df <- plot_dt %>%
    filter(cmp==stage_pair) %>%
    inner_join(
      # mc_df %>% mutate(End=Pos+5e3-1),
      mc_df %>%
        mutate(chr=paste0("chr", chrom)) %>%
        dplyr::select(
          "chr", "end",
          all_of(as.character(pre_stage)),
          all_of(as.character(pro_stage))),
      by = c("chr","end"))

  tmp_df %<>%
    filter(get(pre_stage)>0 & meth_g1>0 & meth_g2 > 0 & get(pro_stage) >0) %>%
    mutate(
      ratio_5hmC = log2((meth_g2) / (meth_g1) ), ## 5hmC
      ratio_5mC = log2((get(pro_stage)) / (get(pre_stage)) )) %>% ## 5mC
    mutate(
      demeth = case_when(
      ratio_5hmC > -1 & ratio_5mC < -1 ~ "active_de",
      TRUE ~ "other")
    )

  gc()
  
  # cor_res <- cor.test(tmp_df$ratio_5hmC, tmp_df$ratio_5mC)
  # print(cor_res)

  p1 <- ggplot(tmp_df, aes(x = ratio_5hmC, y = ratio_5mC, color = category)) +
    # geom_point(aes(color = category), size = 0.1, shape=21) +
    geom_density2d(aes(color = category), size = 1) +
    geom_hline(yintercept = log2(0.5), linetype = "longdash") +
    geom_vline(xintercept = log2(0.5), linetype = "longdash") +
    labs(y = "logFC of 5mC", x = "logFC of 5hmC") +
    scale_color_manual(values = fill_pal) +
    ylim(c(-2.5, 2.5)) +
    labs(title = stage_pair) +
    theme_bw(base_size = 15) +
    theme(
      aspect.ratio = 1,
      panel.grid = element_blank(),
      legend.position = "none",
      plot.margin = unit(c(0, 0, 0, 0), "cm"),
      plot.title = element_text(hjust = .5)
    )
  
  return(p1)

}

pl <- lapply(
  c("2C->4C", "4C->8C", "8C->Morula", "Morula->Blast"),
  plot_5mc_5hmC_ratio
)
cowplot::plot_grid(plotlist = pl, nrow = 1)
```

